@Doc.Management.Api_HostAddress = https://localhost:7282

GET {{Doc.Management.APi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Doc.Management.Api_HostAddress}}/weatherforecast

###
